/** @type {Record<string, string>} ekstensi → tag HTML Bootstrap Icon */
const ExtensionIcons = {
    // ── Document
    pdf:    <i className="bi bi-file-earmark-pdf"></i>,
    doc:    <i className="bi bi-file-earmark-word"></i>,
    docx:   <i className="bi bi-file-earmark-word"></i>,
    dot:    <i className="bi bi-file-earmark-word"></i>,
    dotx:   <i className="bi bi-file-earmark-word"></i>,
    word:   <i className="bi bi-file-earmark-word"></i>,
    xls:    <i className="bi bi-file-earmark-excel"></i>,
    xlsx:   <i className="bi bi-file-earmark-excel"></i>,
    xlsb:   <i className="bi bi-file-earmark-excel"></i>,
    xlsm:   <i className="bi bi-file-earmark-excel"></i>,
    xl:     <i className="bi bi-file-earmark-excel"></i>,
    csv:    <i className="bi bi-file-earmark-spreadsheet"></i>,
    ppt:    <i className="bi bi-file-earmark-ppt"></i>,
    pptx:   <i className="bi bi-file-earmark-ppt"></i>,

    // ── Archive
    zip:    <i className="bi bi-file-earmark-zip"></i>,
    rar:    <i className="bi bi-file-earmark-zip"></i>,
    gz:     <i className="bi bi-file-earmark-zip"></i>,
    gzip:   <i className="bi bi-file-earmark-zip"></i>,
    tar:    <i className="bi bi-file-earmark-zip"></i>,
    tgz:    <i className="bi bi-file-earmark-zip"></i>,
    "7zip": <i className="bi bi-file-earmark-zip"></i>,
    z:      <i className="bi bi-file-earmark-zip"></i>,
    gtar:   <i className="bi bi-file-earmark-zip"></i>,
    sit:    <i className="bi bi-file-earmark-zip"></i>,
    kmz:    <i className="bi bi-file-earmark-zip"></i>,

    // ── Code
    js:     <i className="bi bi-filetype-js"></i>,
    json:   <i className="bi bi-filetype-json"></i>,
    html:   <i className="bi bi-filetype-html"></i>,
    htm:    <i className="bi bi-filetype-html"></i>,
    shtml:  <i className="bi bi-filetype-html"></i>,
    xhtml:  <i className="bi bi-filetype-html"></i>,
    xht:    <i className="bi bi-filetype-html"></i>,
    css:    <i className="bi bi-filetype-css"></i>,
    xml:    <i className="bi bi-filetype-xml"></i>,
    xsl:    <i className="bi bi-filetype-xml"></i>,
    svg:    <i className="bi bi-filetype-svg"></i>,
    php:    <i className="bi bi-filetype-php"></i>,
    php3:   <i className="bi bi-filetype-php"></i>,
    php4:   <i className="bi bi-filetype-php"></i>,
    phtml:  <i className="bi bi-filetype-php"></i>,
    phps:   <i className="bi bi-filetype-php"></i>,
    sh:     <i className="bi bi-terminal"></i>,
    zsh:    <i className="bi bi-terminal"></i>,
    jar:    <i className="bi bi-filetype-java"></i>,

    // ── Image
    jpg:    <i className="bi bi-file-earmark-image"></i>,
    jpeg:   <i className="bi bi-file-earmark-image"></i>,
    jpe:    <i className="bi bi-file-earmark-image"></i>,
    png:    <i className="bi bi-file-earmark-image"></i>,
    gif:    <i className="bi bi-file-earmark-image"></i>,
    webp:   <i className="bi bi-file-earmark-image"></i>,
    bmp:    <i className="bi bi-file-earmark-image"></i>,
    tif:    <i className="bi bi-file-earmark-image"></i>,
    tiff:   <i className="bi bi-file-earmark-image"></i>,
    ico:    <i className="bi bi-file-earmark-image"></i>,
    psd:    <i className="bi bi-file-earmark-image"></i>,
    ai:     <i className="bi bi-file-earmark-image"></i>,

    // ── Audio
    mp3:    <i className="bi bi-file-earmark-music"></i>,
    mp2:    <i className="bi bi-file-earmark-music"></i>,
    mpga:   <i className="bi bi-file-earmark-music"></i>,
    wav:    <i className="bi bi-file-earmark-music"></i>,
    ogg:    <i className="bi bi-file-earmark-music"></i>,
    aac:    <i className="bi bi-file-earmark-music"></i>,
    flac:   <i className="bi bi-file-earmark-music"></i>,
    wma:    <i className="bi bi-file-earmark-music"></i>,
    m4a:    <i className="bi bi-file-earmark-music"></i>,
    aif:    <i className="bi bi-file-earmark-music"></i>,
    aiff:   <i className="bi bi-file-earmark-music"></i>,
    aifc:   <i className="bi bi-file-earmark-music"></i>,
    mid:    <i className="bi bi-file-earmark-music"></i>,
    midi:   <i className="bi bi-file-earmark-music"></i>,
    ac3:    <i className="bi bi-file-earmark-music"></i>,
    au:     <i className="bi bi-file-earmark-music"></i>,
    ra:     <i className="bi bi-file-earmark-music"></i>,
    ram:    <i className="bi bi-file-earmark-music"></i>,

    // ── Video
    mp4:    <i className="bi bi-file-earmark-play"></i>,
    webm:   <i className="bi bi-file-earmark-play"></i>,
    avi:    <i className="bi bi-file-earmark-play"></i>,
    mov:    <i className="bi bi-file-earmark-play"></i>,
    qt:     <i className="bi bi-file-earmark-play"></i>,
    flv:    <i className="bi bi-file-earmark-play"></i>,
    wmv:    <i className="bi bi-file-earmark-play"></i>,
    mpg:    <i className="bi bi-file-earmark-play"></i>,
    mpeg:   <i className="bi bi-file-earmark-play"></i>,
    mpe:    <i className="bi bi-file-earmark-play"></i>,
    m4u:    <i className="bi bi-file-earmark-play"></i>,
    "3gp":  <i className="bi bi-file-earmark-play"></i>,
    "3g2":  <i className="bi bi-file-earmark-play"></i>,
    f4v:    <i className="bi bi-file-earmark-play"></i>,
    srt:    <i className="bi bi-file-earmark-play"></i>,
    vtt:    <i className="bi bi-file-earmark-play"></i>,

    // ── Text
    txt:    <i className="bi bi-file-earmark-text"></i>,
    text:   <i className="bi bi-file-earmark-text"></i>,
    log:    <i className="bi bi-file-earmark-text"></i>,
    rtf:    <i className="bi bi-file-earmark-text"></i>,
    rtx:    <i className="bi bi-file-earmark-richtext"></i>,

    // ── Security / Certificate
    pem:    <i className="bi bi-file-earmark-lock"></i>,
    crt:    <i className="bi bi-file-earmark-lock"></i>,
    cer:    <i className="bi bi-file-earmark-lock"></i>,
    der:    <i className="bi bi-file-earmark-lock"></i>,
    csr:    <i className="bi bi-file-earmark-lock"></i>,
    p12:    <i className="bi bi-file-earmark-lock"></i>,
    p7c:    <i className="bi bi-file-earmark-lock"></i>,
    p7m:    <i className="bi bi-file-earmark-lock"></i>,
    p7s:    <i className="bi bi-file-earmark-lock"></i>,
    p7a:    <i className="bi bi-file-earmark-lock"></i>,
    p7r:    <i className="bi bi-file-earmark-lock"></i>,
    p10:    <i className="bi bi-file-earmark-lock"></i>,
    rsa:    <i className="bi bi-file-earmark-lock"></i>,
    crl:    <i className="bi bi-file-earmark-lock"></i>,
    pgp:    <i className="bi bi-shield-lock"></i>,
    gpg:    <i className="bi bi-shield-lock"></i>,

    // ── Binary / Executable
    exe:    <i className="bi bi-file-earmark-binary"></i>,
    dll:    <i className="bi bi-file-earmark-binary"></i>,
    bin:    <i className="bi bi-file-earmark-binary"></i>,
    so:     <i className="bi bi-file-earmark-binary"></i>,
    className:  <i className="bi bi-file-earmark-binary"></i>,

    // ── E-mail / Calendar / Contact
    eml:    <i className="bi bi-envelope"></i>,
    ics:    <i className="bi bi-calendar-event"></i>,
    ical:   <i className="bi bi-calendar-event"></i>,
    vcf:    <i className="bi bi-person-vcard"></i>,

    // ── 3D / Model
    stl:    <i className="bi bi-box"></i>,

    // ── Geo
    kml:    <i className="bi bi-geo-alt"></i>,
};

export default ExtensionIcons;